from . import base

DEBUG = False
DATABASES = base.DATABASES
INSTALLED_APPS = base.INSTALLED_APPS

SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
